name: Create branch and pr on issue assigned

run-name: Create branch and pr for issue ${{ github.event.issue.number }}

on:
  issues:
    types: [assigned]

jobs:
  create-branch:
    name: Create branch
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: develop
        fetch-depth: 0
    
    - name: Create branch
      if: ${{ github.event.issue.labels[0].name == 'FTR' || github.event.issue.labels[0].name == 'HTX' || github.event.issue.labels[0].name == 'RLS' }}
      run: |
        git config --local user.email "
        git config --local user.name "
        git checkout -b ${{ github.event.issue.labels[0].name }}-${{ github.event.issue.number }}
        git push --set-upstream origin ${{ github.event.issue.labels[0].name }}-${{ github.event.issue.number }}

  create-pr:
    name: Create pull request
    needs: create-branch
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - name: Create pull request
      if: ${{ github.event.issue.labels[0].name == 'FTR' || github.event.issue.labels[0].name == 'HTX' || github.event.issue.labels[0].name == 'RLS' }}
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GH_TOKEN }}
        commit-message: "Create pull request for issue ${{ github.event.issue.number }}"
        title: "${{ github.event.issue.title }}"
        body: "${{ github.event.issue.body }}"
        branch: ${{ github.event.issue.labels[0].name }}-${{ github.event.issue.number }}
        base: develop
        labels: ${{ github.event.issue.labels[0].name }}
        team-reviewers: buildtheblock/reviewers
        assignees: ${{ github.event.issue.assignee.login }}
        delete-branch: true
