name: Automatically create a new branch and pull request when an issue is assigned

on:
  issues:
    types: [assigned]

jobs:
  create-branch-and-pull-request:
    runs-on: ubuntu-latest

    steps:
    - name: Check the branch does not already exist
      if: ${{ github.event.issue.labels[0] == 'FTR' || github.event.issue.labels[0] == 'HTX' || github.event.issue.labels[0] == 'RLS' }}
      run: |
        git ls-remote --heads origin ${{ github.event.issue.labels[0] }}-${{ github.event.issue.number }}
        if [ $? -eq 0 ]; then
          echo ""
          exit 1
        fi

    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: develop
        fetch-depth: 0
    
    - name: Create branch
      if: ${{ github.event.issue.labels[0] == 'FTR' || github.event.issue.labels[0] == 'HTX' || github.event.issue.labels[0] == 'RLS' }}
      run: |
        git config --local user.email "
        git config --local user.name "
        git checkout -b ${{ github.event.issue.labels[0] }}-${{ github.event.issue.number }}
        git push --set-upstream origin ${{ github.event.issue.labels[0] }}-${{ github.event.issue.number }}

    - name: Create pull request
      if: ${{ github.event.issue.labels[0] == 'FTR' || github.event.issue.labels[0] == 'HTX' || github.event.issue.labels[0] == 'RLS' }}
      run:
        gh pr create --title "${{ github.event.issue.title }}" --body "${{ github.event.issue.body }}" --base develop --head ${{ github.event.issue.labels[0] }}-${{ github.event.issue.number }}