name: Create branch and pr on issue assigned

run-name: Create branch and pr for issue /#${{ github.event.issue.number }}

on:
  issues:
    types: [assigned]

env:
  IS_CORRECT_LABEL: ${{ github.event.issue.labels[0].name == 'FTR' || github.event.issue.labels[0].name == 'HTX' || github.event.issue.labels[0].name == 'RLS' }}

jobs:
  create-branch:
    name: Create branch
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: develop
        fetch-depth: 0
    
    - name: Create branch
      if: $IS_CORRECT_LABEL
      run: |
        git config --local user.email "
        git config --local user.name "
        git checkout -b ${{ github.event.issue.labels[0].name }}-${{ github.event.issue.number }}
        git push --set-upstream origin ${{ github.event.issue.labels[0].name }}-${{ github.event.issue.number }}

  create-pr:
    name: Create pull request
    needs: create-branch
    runs-on: ubuntu-latest
    steps:
    - name: Create pull request
      if: $IS_CORRECT_LABEL
      run:
        gh pr create --title "${{ github.event.issue.title }}" --body "${{ github.event.issue.body }}" --base develop --head ${{ github.event.issue.labels[0].name }}-${{ github.event.issue.number }}
